config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: {
    registrations: 'usuarios/registrations'
  }

  resources :torneios, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'inscrever'
      get 'inscricoes'
    end
  end

  resources :usuarios, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'torneios#index'
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  # Validações
  validates :nome, presence: true
  validates :perfil, presence: true, inclusion: { in: ['Organizador', 'Participante'] }
end

app/controllers/usuarios/confirmations_controller.rb
# frozen_string_literal: true

class Usuarios::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/usuarios/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/usuarios/passwords_controller.rb
# frozen_string_literal: true

class Usuarios::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/usuarios/registrations_controller.rb
class Usuarios::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :perfil])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :perfil])
  end
end

app/controllers/usuarios/sessions_controller.rb
# frozen_string_literal: true

class Usuarios::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/usuarios/unlocks_controller.rb
# frozen_string_literal: true

class Usuarios::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :autorizar_organizador, only: [:new, :create, :edit, :update, :destroy]

  def index
    @usuarios = Usuario.all
    puts "Usuários carregados no controlador: #{@usuarios.inspect}" # Log para depuração
  end

  def show
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      puts "Usuário criado com sucesso: #{@usuario.inspect}" 
      redirect_to usuarios_path, notice: 'Usuário criado com sucesso!'
    else
      puts "Erro ao criar usuário: #{@usuario.errors.full_messages}" 
      render :new
    end
  end

  def edit
  end

  def update
    if @usuario.update(usuario_params)
      redirect_to @usuario, notice: 'Usuário atualizado com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    @usuario.destroy
    redirect_to usuarios_path, notice: 'Usuário excluído com sucesso!'
  end

  private

  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  def usuario_params
    params.require(:usuario).permit(:nome, :email, :perfil, :password, :password_confirmation)
  end

  def autorizar_organizador
    unless current_usuario.perfil == 'Organizador'
      redirect_to torneios_path, alert: 'Acesso negado. Somente organizadores podem realizar esta ação.'
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/edit.html.erb
<h1>Editar Usuário</h1>

<%= form_with model: @usuario, local: true do |form| %>
  <div>
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :perfil %>
    <%= form.select :perfil, ['Organizador', 'Participante'] %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.submit 'Atualizar Usuário' %>
  </div>
<% end %>

<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/index.html.erb
<div class="card">
  <h1>Usuários</h1>

  <% if current_usuario.perfil == 'Organizador' %>
    
  <% end %>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Perfil</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr>
          <td><%= usuario.nome %></td>
          <td><%= usuario.email %></td>
          <td><%= usuario.perfil %></td>
          <td>
            <%= link_to 'Ver', usuario, class: 'btn btn-secondary' %>
            <% if current_usuario.perfil == 'Organizador' %>
              <%= link_to 'Editar', edit_usuario_path(usuario), class: 'btn btn-secondary' %>
              <%= button_to 'Excluir', usuario, method: :delete, data: { confirm: 'Tem certeza?', turbo: false }, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/usuarios/new.html.erb
<%= form_with(model: @usuario, url: usuarios_path) do |f| %>
  <%= render "shared/error_messages", resource: @usuario %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :perfil %><br />
    <%= f.select :perfil, ['Organizador', 'Participante'] %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> caracteres no mínimo)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Cadastrar" %>
  </div>
<% end %>

app/views/usuarios/show.html.erb
<h1><%= @usuario.nome %></h1>
<p>Email: <%= @usuario.email %></p>
<p>Perfil: <%= @usuario.perfil %></p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %>
<%= link_to 'Voltar', usuarios_path %>