config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: {
    registrations: 'usuarios/registrations'
  }

  resources :torneios, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'inscrever'
      get 'inscricoes'
    end
  end

  resources :usuarios, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  root 'torneios#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gerenciador Torneios" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
  <nav class="container">
    <%= link_to 'Torneios', torneios_path %>
    <% if usuario_signed_in? && current_usuario.perfil == 'Organizador' %>
      <%= link_to 'Usuários', usuarios_path, class: 'btn btn-secondary' %>
    <% end %>
    <% if usuario_signed_in? %>
      <span>Olá, <%= current_usuario.nome %></span>
      <%= button_to 'Sair', destroy_usuario_session_path, method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'Entrar', new_usuario_session_path, class: 'btn' %>
      <%= link_to 'Cadastrar', new_usuario_registration_path, class: 'btn' %>
    <% end %>
  </nav>
</header>

    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>